name = "CFLPLib"
uuid = "3771e204-432d-45a9-9661-5d0025a53671"
authors = ["Rafael Martinelli"]
version = "1.0.0"

[deps]
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
ZipFile = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
